- _data/glossary/en/message-header.yaml
> Change Bitcoin.org ref to Dash.org

- _includes/devdoc/example_intro.md
- _includes/devdoc/example_p2p_networking.md
- _includes/devdoc/example_testing.md
- _includes/devdoc/example_transactions.md
- _includes/layout/base/head-menu.html
- _includes/references.md
- _includes/templates/index.html
- en/developer-examples.md
- scripts/bloom_filter.py
- scripts/regtest_transaction_simple_spending_example.sh
Update the examples section and add back to navigation
> Examples updated

- _includes/devdoc/ref_bips.md
- _includes/layout/base/bip-table.html
- _includes/layout/base/dip-table.html
- en/developer-reference.md
- Include tables for BIPs/DIPs linked to source repos
> Add BIP reference section

- README.md
- _includes/helpers/subhead-links.md
- _includes/references.md
- docs/contributing-to-developer-documentation.md
- docs/setting-up-your-environment.md
- docs/working-with-github.md
- en/developer-examples.md
- en/developer-glossary.html
- en/developer-guide.md
- en/developer-reference.md
- js/main.js
> Update links to point at correct GH account / repo 

- _includes/layout/base/footer-license.html
Resolves dash-docs/dash-docs.github.io#3
> Add Dash Project to copyright

- .travis.yml
Resolves issue with Bundler 1.16.0 build
> config - Travis bundler update

- _includes/devdoc/guide_dash_features.md
- Clarify confirmation meaning
- Update fee info
> content - InstantSend

- doxygen/Doxyfile-dashdocs
> config - Update Doxygen project number to current Dash Core version

- CONTRIBUTING.md
- scripts/build-install-doxygen.sh
- scripts/generateDocumentationAndDeploy.sh
- Minor documentation and script comment changes
> doc - Minor documentation and script comment changes

- _includes/devdoc/guide_dash_features.md
Add details on the PrivateSend process and fees
> [Content] Expand PrivateSend details

- _includes/devdoc/guide_dash_features.md
> [Content] Embed Matt Robertson InstantSend video from the 2017 Dash Conf

- _includes/devdoc/dash-core/rpcs/rpcs/gobject.md
- Update example and Vote Info field
- Closes #24
> [Content] RPC GObject GetVotes outpoint shortened

- .travis.yml
- Temporary update for deploy 1.9 issue (travis-ci/travis-ci#9312)
> config - Travis config update

- _includes/devdoc/ref_p2p_networking.md
> [Content] P2P - Deprecate count in MnGet

- _includes/devdoc/dash-core/rpcs/rpcs/masternodelist.md
- Add new modes
- Update example
- Closes #46
> [RPC] Update MasternodeList

- _data/glossary/en/devnet.yaml
- _data/glossary/en/regression-test-mode.yaml
- _data/glossary/en/testnet.yaml
- _includes/devdoc/example_intro.md
- _includes/devdoc/example_testing.md
- _includes/devdoc/ref_p2p_networking.md
- Description in examples section
- Glossary entry and updated testnet/regtest
Closes #36
> [Content] Add devnet details

- _includes/devdoc/guide_dash_features.md
> [Content] - Update InstantSend with network specific conf thresholds

- _includes/devdoc/guide_dash_features.md
> [Content] - Update PrivateSend collateral info for protocol >70208 change

- _includes/devdoc/ref_p2p_networking.md
> [Content] - Update Reject P2P message to cover IS, PS, and Governance

- _includes/devdoc/dash-core/rpcs/rpcs/gobject.md
- Add mode parameter
- Closes #52
> [Content] - RPC - Update Gobject message

- _includes/devdoc/guide_dash_features.md
- _includes/devdoc/ref_p2p_networking.md
> [P2P] Add PrivateSend input count info

- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/ref_p2p_networking.md
- Protocol version change
- Release note highlights
> v12.3 release updates

- _includes/layout/base/head-menu.html
- _sass/screen.scss
- _templates/bitcoin-for-developers.html
- _templates/dash-for-developers.html
- _translations/en.yml
- doxygen/doxygen_header.html
Dashify "for developers" page and remove button icon
> Dash for devs updates

- _includes/devdoc/ref_p2p_networking.md
Correct hexdump issue reported in dashpay/dash#2160
> Content - Fix govobjvote hexdump

- _includes/templates/index.html
- en/developer-documentation.md
> Add ChainRider REST service doc link

- _includes/devdoc/dash-core/rpcs/rpcs/getnetworkinfo.md
- Add missing `networkactive` parameter
- Closes #85
> Content - RPC - getnetworkinfo

- _includes/devdoc/ref_transactions.md
DIP 2-4 details
Update raw tx info
> V13.0 special txs

- _includes/devdoc/guide_dash_features.md
Add Auto-IS info
Update PS collateral
MN sync minor changes
> V0.13.0 guide dash features

- doxygen/Doxyfile-dashdocs
Remove some of the Doxygen graphs that seemed to be causing Github Pages build timeouts
> Github Pages build debug

- .travis.yml
Remove temporary fix for dpl 1.9 issue (#44 - fixes
travis-ci/travis-ci#9312)
> Config - Travis deploy

- _autocrossref.yaml
- _includes/devdoc/dash-core/rpcs/rpcs/decoderawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/getrawtransaction.md
- _includes/devdoc/ref_transactions.md
- _includes/references.md
Clarify special transaction details
> V0.13.0 special tx update

- doxygen/Doxyfile-dashdocs
> [Config] Update Doxygen project number to current Dash Core version

- _autocrossref.yaml
- _config.yml
- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/getrawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/getspecialtxes.md
- _includes/helpers/summaries.md
- _includes/layout/base/rpc-table.html
- _includes/references.md
- en/developer-reference.md
Related to dashpay/dash#2688
Closes #105
> RPC - Add getspecialtxes RPC

- _includes/devdoc/dash-core/rpcs/rpcs/protx.md
I have tested this, and it works for P2SH addresses.
> removed p2pkh constraint on protx register_fund

- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/masternodelist.md
- _includes/devdoc/dash-core/rpcs/rpcs/protx.md
- _includes/helpers/vars.md
- _includes/layout/base/rpc-table.html
> V0.13.2 RPC Masternode lists

- _data/glossary/en/high-priority-transaction.yaml
- _data/glossary/en/minimum-relay-fee.yaml
- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/bls.md
- _includes/devdoc/dash-core/rpcs/rpcs/debug.md
- _includes/devdoc/dash-core/rpcs/rpcs/estimatepriority.md
- _includes/devdoc/dash-core/rpcs/rpcs/estimatesmartpriority.md
- _includes/devdoc/dash-core/rpcs/rpcs/getinfo.md
- _includes/devdoc/dash-core/rpcs/rpcs/getnetworkinfo.md
- _includes/devdoc/dash-core/rpcs/rpcs/masternodebroadcast.md
- _includes/devdoc/dash-core/rpcs/rpcs/prioritisetransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/sentinelping.md
- _includes/devdoc/guide_transactions.md
- _includes/helpers/summaries.md
- _includes/layout/base/rpc-table.html
- Updates related to removing coin priority (`getinfo`, `getnetworkinfo`, `estimate*priority`, `prioritisetransaction`)
- Minor update of `debug`
Related to dashpay/dash#2768
> V0.14.0 Coin priority (RPC and Guide) and Debug

- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/getblock.md
- _includes/devdoc/dash-core/rpcs/rpcs/getrawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/gettransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/listsinceblock.md
- _includes/devdoc/dash-core/rpcs/rpcs/listtransactions.md
- _includes/helpers/vars.md
- _includes/layout/base/rpc-table.html
Add chainlock to numerous RPCs `getrawtransaction`, `gettransaction`, `getblock`, `listsinceblock`, `listtransactions`
Related to dashpay/dash#2743
> V0.14.0 rpc chainlock param

- _includes/devdoc/ref_p2p_networking.md
- Add hexdumps for `senddsq`, `mnauth`, and `islock` messages
- Add hexdumps for signing session messages
> V0.14.0 P2P Add hexdumps for new misc and signing session messages

- _includes/devdoc/ref_p2p_networking.md
- _includes/devdoc/ref_transactions.md
Update CbTx to version 2
Add new quorum fields to `mnlistdiff`
> V0.14.0 DIP4 CbTx and mnlistdiff updates

- _includes/devdoc/dash-core/rpcs/rpcs/gobject.md
- _includes/devdoc/guide_dash_features.md
- _includes/devdoc/ref_p2p_networking.md
- _includes/helpers/vars.md
- PrivateSend change
- Refactor MN Sync info to archive details of old system
- Update Governance section
> V0.14.0 Guide updates

- _includes/layout/base/html-head.html
- js/analytics.js
Re-enable DNT-compliant IP-anonymized analytics
> Config - analytics

- doxygen/Doxyfile-dashdocs
Merge after dashpay/dash master branch contains v0.14
> Config - Update version in Doxyfile to 0.14.0.0

- _includes/devdoc/guide_dash_features.md
- _includes/templates/index.html
- Describe v0.14.0 PoSe scoring
See https://thephez.github.io/en/developer-guide#proof-of-service
> Content - Add Proof of Service section

- _includes/devdoc/ref_p2p_networking.md
> P2P - Deprecate inclusion of entry count in dssu message

- _autocrossref.yaml
- _config.yml
- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/getmerkleblocks.md
- _includes/helpers/summaries.md
- _includes/layout/base/rpc-table.html
- _includes/references.md
- en/developer-reference.md
New RPC
Related to dashpay/dash#2894
> RPC - Add getmerkleblocks

- _includes/devdoc/dash-core/rpcs/rpcs/quorum.md
> RPC add quorum memberof

- _includes/devdoc/dash-core/rpcs/rpcs/getrawtransaction.md
> RPC - Update getrawtransaction

- _data/glossary/en/spork.yaml
- _data/glossary/en/x11.yaml
- _includes/devdoc/guide_block_chain.md
- _includes/devdoc/guide_dash_features.md
- _includes/devdoc/ref_p2p_networking.md
- _includes/templates/index.html
docs.dash.org switched from `latest` to `stable`
Fixes #154
> Content - Update docs.dash.org links

- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/fundrawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/gettxout.md
- _includes/layout/base/rpc-table.html
> RPC - Update fundrawtransaction and gettxout

- _includes/devdoc/guide_dash_features.md
- Revised InstantSend
- Historical ref section for deprecated content
- Move old MN sync content to historical section
> Guide - Update Dash features section

- _includes/devdoc/guide_dash_features.md
- _includes/devdoc/ref_p2p_networking.md
- Pool creation strategy changed (related to dashpay/dash#3085)
- Denom info updated
> PrivateSend updates

- _autocrossref.yaml
- _config.yml
- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/getbestchainlock.md
- _includes/helpers/summaries.md
- _includes/layout/base/rpc-table.html
- _includes/references.md
- en/developer-reference.md
> RPC - Add getbestchainlock

- _autocrossref.yaml
- _config.yml
- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/combinerawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/createrawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/decoderawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/sendrawtransaction.md
- _includes/devdoc/dash-core/rpcs/rpcs/signrawtransaction.md
- _includes/helpers/summaries.md
- _includes/layout/base/rpc-table.html
- _includes/references.md
- en/developer-reference.md
Related to dashpay/dash#3096 and dashpay/dash#3102
> RPC - Add combinerawtransaction

- _autocrossref.yaml
- _config.yml
- _includes/devdoc/dash-core/rpcs/quick-reference.md
- _includes/devdoc/dash-core/rpcs/rpcs/getpoolinfo.md
- _includes/devdoc/dash-core/rpcs/rpcs/getprivatesendinfo.md
- _includes/helpers/summaries.md
- _includes/layout/base/rpc-table.html
- _includes/references.md
- en/developer-reference.md
> RPC - add getprivatesendinfo

- Makefile
- _includes/devdoc/fragment_reviews_needed.md
- _includes/templates/index.html
- _templates/dash-for-developers.html
- _templates/vocabulary.html
- en/developer-examples.md
- en/developer-glossary.html
- en/developer-guide.md
- en/developer-reference.md
Future traffic should be directed to the new site at https://dashcore.readme.io
> Add deprecation notice for this site

- _includes/devdoc/dash-core/rpcs/rpcs/quorum.md
> RPC - add pubKeyOperator to quorum list

- doxygen/Doxyfile-dashdocs
> chore: bump doxygen version number
